obj-$(CONFIG_CAPEBUS_BONE_DVI)		+= bone-dvi-cape.o
obj-$(CONFIG_CAPEBUS_BONE_GEIGER)	+= bone-geiger-cape.o
obj-$(CONFIG_CAPEBUS_BONE_LCD)		+= bone-lcd-cape.o
obj-$(CONFIG_CAPEBUS_BONE_GENERIC)	+= bone-generic-cape.o
