#
# Makefile for CAPEBUS devices
#

obj-$(CONFIG_CAPEBUS_CORE)		+= capebus-probe.o \
					   capebus-driver.o capebus-sysfs.o
obj-$(CONFIG_CAPEBUS_CORE)		+= boards/
obj-$(CONFIG_CAPEBUS_CORE)		+= capes/
